// Code generated by mockery v2.52.4. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/stipochka/web_service/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// GrpcClient is an autogenerated mock type for the GrpcClient type
type GrpcClient struct {
	mock.Mock
}

// GetAllRecords provides a mock function with given fields: ctx
func (_m *GrpcClient) GetAllRecords(ctx context.Context) ([]models.Record, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllRecords")
	}

	var r0 []models.Record
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]models.Record, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []models.Record); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Record)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRecordById provides a mock function with given fields: ctx, id
func (_m *GrpcClient) GetRecordById(ctx context.Context, id int) (models.Record, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetRecordById")
	}

	var r0 models.Record
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (models.Record, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) models.Record); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(models.Record)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewGrpcClient creates a new instance of GrpcClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGrpcClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *GrpcClient {
	mock := &GrpcClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
